### ISSUE TITLE
Don't repeat yourself

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_x_s-a#17]
Un principio básico de programación es "[Don't repeat yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)". En el código que habéis escrito para generar cartas habéis definido 9 funciones que son prácticamente iguales: https://github.com/aigora/twIE_2021-proyecto_x_s-a/blob/0f793a2909672ab581914125a375bda14e45b400/Programa%20generador%20de%20cartas.c#L18-L26

Debéis redefinirlas (probablemente sólo necesitéis una única función) para evitar esta repetición, usando la abstracción y los vectores. 

El uso de estas funciones os obliga a, nuevamente, repetir código casi idéntico en los bucles `switch-case`:

https://github.com/aigora/twIE_2021-proyecto_x_s-a/blob/0f793a2909672ab581914125a375bda14e45b400/Programa%20generador%20de%20cartas.c#L262-L287

También debéis reformularlos.

**Comment by Marco-Antonio-Pinto** [comment]
Ya está corregido este apartado. 
Para ello, se ha cambiado todas las funciones por una única función, que tiene como argumento el número de cartas que desee sumar  y un vector, que es donde se almacenan el valor de las cartas a sumar.
