### ISSUE TITLE
Uso de system

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_x_s-a#18]
Debéis evitar el uso de system porque hace llamadas a comandos del sistema operativo y, por tanto, no es portable: lo que funciona en windows no funciona en linux o mac, y viceversa:

https://github.com/aigora/twIE_2021-proyecto_x_s-a/blob/0f793a2909672ab581914125a375bda14e45b400/Programa%20generador%20de%20cartas.c#L52

Una solución sencilla es emplear los ANSI escape codes. Hablé de ellos en [una respuesta en el canal de tutorías](https://teams.microsoft.com/l/message/19:98e916bb4a3a46a6ac3150257541425d@thread.tacv2/1615334973963?tenantId=6afea85d-c323-4270-b69d-a4fb3927c254&groupId=3477ddd6-cbb2-4bb5-ad31-ecefaebf2091&parentMessageId=1615327042869&teamName=Inform%C3%A1tica%2056IE%20(2020-21)&channelName=Tutor%C3%ADas&createdTime=1615334973963).

Por ejemplo, para borrar la pantalla probad con:
`printf("\033[2J");`

No olvidéis que necesitaréis [Windows Terminal](https://github.com/microsoft/terminal#installing-and-running-windows-terminal).

**Comment by Marco-Antonio-Pinto** [comment]
Muy buenas tardes, llevo un par de días probando el hecho de cambiar las funciones "system("cls")", por la función que usted nos recomendó para borrar la pantalla. 
Tengo que admitir que ha funcionado para borrar lo que había en pantalla, pero... no sé por que, si escribo 8 líneas, uso la función, y me borra las 8 líneas, pero me escribe en la novena. y no en la primera como sería lo suyo. 
Además, si cambiamos todas las funciones "system" por la recomendada. a la hora de compilar, no sé imprimen los colores de las cartas, se imprime una cosa rara, que es como que una flecha, seguido de un número con una m; una antes del texto y una después de él. debido a que hay dos funciones de colores, una para darle color al texto y otra para restablecerlo al predeterminado. Bueno... de todas formas, espero en verdad no sea un inconveniente,  pues... he buscado vídeos sobre los ANSI ESCAPES CODES (que no terminaban trayendo mucha información al respecto),  y buscado en foros (pero sin éxito). Ya no sé que hacer para corregirlo. Otros vídeos, decían de cambiar un par de cosas en los ajustes del mismo sistema, pero claro... aunque lo cambie yo, seguiría dando lo mismo, pues yo lo podría compilar perfectamente, pero otra persona no, y por ende no sería "portable", así que, con mi grupo hemos decidido dejarlo así.
PD: Compilandolo desde el Windows Terminal, también da errores de compilación, si lo compilamos con la función recomendada.

**Comment by oscarperpinan** [comment]
Quizás no lo he expresado con claridad, pero lo que os planteo en esta issue es una exigencia, no una recomendación que podáis decidir aceptar o no. 

Este miércoles en clase podemos verlo juntos.

**Comment by Marco-Antonio-Pinto** [comment]
Está bien, Dº Óscar

**Comment by Marpiki11** [comment]
Ya se ha resuelto el programa.
