### ISSUE TITLE
Texto dentro de código

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_x_s-a#19]
He comprobado que escribís largos mensajes de texto dentro del código:

https://github.com/aigora/twIE_2021-proyecto_x_s-a/blob/0f793a2909672ab581914125a375bda14e45b400/prueba%20scaperoom.c#L77-L92

Es una mala práctica de programación que debéis evitar. Los textos que queráis mostrar en pantalla debéis almacenarlos en ficheros y leerlos con `fscanf` durante la ejecución del programa. De esta forma el código es más legible y más fácil de mantener, y los cambios que queráis realizar en los textos no os obligarán a recompilar el código.

**Comment by Marco-Antonio-Pinto** [comment]
Ya está corregido el error
