### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_x_s-a#3]
Hola,

He revisado el README:

- La propuesta es adecuada. Adelante.
- Usad formato de lista para los integrantes.
- Podéis enlazar cada usuario a su página web de github.
- El README no es un tablón para colgar mensajes. Tenéis un canal de discusión [aquí](https://github.com/orgs/aigora/teams/proyecto_x_s-a/discussions). Por favor, eliminad la última sección del README.

**Comment by Marco-Antonio-Pinto** [comment]
Perfecto, ya he resuelto los problemas del punto 2 y 4. Ahora miro del punto 3. Gracias por los consejos.

**Comment by Marco-Antonio-Pinto** [comment]
Okey, ya está todo resuelto y listo para en la próxima reunión, comenzar con el diseño del programa.
